# Generated by Django 5.0.14 on 2026-09-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pajak', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dicetak_pada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billing',
                'db_table': 'billing',
            },
        ),
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('tipe', models.CharField(choices=[('MAKANAN_UTAMA', 'Makanan Utama'), ('APPETIZER', 'Appetizer'), ('MINUMAN', 'Minuman')], max_length=20)),
            ],
            options={
                'verbose_name': 'Kategori Produk',
                'verbose_name_plural': 'Kategori Produk',
                'db_table': 'kategori_produk',
            },
        ),
        migrations.CreateModel(
            name='LaporanPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('MINGGUAN', 'Mingguan'), ('BULANAN', 'Bulanan')], max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_penjualan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laporan Penjualan',
                'verbose_name_plural': 'Laporan Penjualan',
                'db_table': 'laporan_penjualan',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_meja', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'db_table': 'pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('KASIR', 'Kasir')], max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'db_table': 'pengguna',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('TUNAI', 'Tunai'), ('DEBIT', 'Debit'), ('KARTU_KREDIT', 'Kartu Kredit')], max_length=20)),
                ('jumlah_diterima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kembalian', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomor_referensi', models.CharField(blank=True, default='', max_length=50)),
                ('dibayar_pada', models.DateTimeField(auto_now_add=True)),
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='core.billing')),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_list', to='core.pengguna')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'db_table': 'pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pesanan', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai'), ('DIBAYAR', 'Dibayar'), ('DIBATALKAN', 'Dibatalkan')], default='BARU', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesanan_list', to='core.pelanggan')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanan',
                'db_table': 'pesanan',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.AddField(
            model_name='billing',
            name='pesanan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.pesanan'),
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('status_stok', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('HABIS', 'Habis')], default='HABIS', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk_list', to='core.kategoriproduk')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'db_table': 'produk',
            },
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_list', to='core.pesanan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_pesanan_list', to='core.produk')),
            ],
            options={
                'verbose_name': 'Detail Pesanan',
                'verbose_name_plural': 'Detail Pesanan',
                'db_table': 'detail_pesanan',
            },
        ),
    ]
