# Generated by Django 5.0.14 on 2026-09-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kategoriproduk_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='dikonfirmasi_kasir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_dikonfirmasi_list', to='core.pengguna'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='metode_dipilih',
            field=models.CharField(choices=[('TUNAI', 'Tunai'), ('QRIS', 'QRIS (Non Tunai)')], default='TUNAI', max_length=20),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='metode',
            field=models.CharField(choices=[('TUNAI', 'Tunai'), ('QRIS', 'QRIS (Non Tunai)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Menunggu Pembayaran'), ('DIBAYAR', 'Dibayar'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='BARU', max_length=20),
        ),
        migrations.CreateModel(
            name='TransaksiGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyedia', models.CharField(default='MOCK', max_length=30)),
                ('kode_bayar', models.CharField(max_length=60, unique=True)),
                ('qr_string', models.TextField(blank=True, default='')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Pembayaran'), ('DIBAYAR', 'Dibayar'), ('GAGAL', 'Gagal'), ('KEDALUWARSA', 'Kedaluwarsa')], default='MENUNGGU', max_length=20)),
                ('kedaluwarsa_pada', models.DateTimeField(blank=True, null=True)),
                ('dibayar_pada', models.DateTimeField(blank=True, null=True)),
                ('notifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_list', to='core.pesanan')),
            ],
            options={
                'verbose_name': 'Transaksi Gateway',
                'verbose_name_plural': 'Transaksi Gateway',
                'db_table': 'transaksi_gateway',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.AddConstraint(
            model_name='transaksigateway',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'MENUNGGU')), fields=('pesanan',), name='satu_transaksi_menunggu_per_pesanan'),
        ),
    ]
